TRAINER:
  model_name: van
  optimizer: adam
  scheduler: ReduceLROnPlateau
  lr: 1.0e-4
  loss_fn: bce
  n_epochs: 20
  metric:
    - acc
    - f1
  early_stopping_target: val_f1
  early_stopping_patience: 5
  early_stopping_mode: max

DATAMODULE:
  train_img_path: train
  test_img_path: test
  val_size: 0.3
  img_size: 384
  batch_size: 16
  num_workers: 2
  seed: 999

seed: 999

