TRAINER:
  model_name: resnet101
  optimizer: adam
  scheduler: ReduceLROnPlateau
  lr: 1.0e-4
  loss_fn: bce
  n_epochs: 20
  metric:
    - acc
    - f1
  early_stopping_target: val_accuracy
  early_stopping_patience: 10
  early_stopping_mode: max

DATAMODULE:
  train_img_path: train
  test_img_path: test
  val_size: 0.3
  img_size: 384
  batch_size: 32
  num_workers: 2
  seed: 999

seed: 999

